// This file is auto-generated by @hey-api/openapi-ts

export const replicaUUID_parameterSchema = {
    type: 'string',
    format: 'uuid',
    description: 'The replica unique identifier (UUID)',
    example: '03db5651-cb61-4bdf-9ef0-89561f7c9c53'
} as const;

export const trainingID_parameterSchema = {
    type: ['number', 'null'],
    description: 'The unique identifier of the knowledge base entry',
    example: 12345
} as const;

export const WebhookRequestSchema = {
    type: 'object',
    properties: {
        type: {
            type: 'string'
        },
        table: {
            type: 'string'
        },
        schema: {
            type: 'string'
        },
        record: {
            type: 'object',
            properties: {
                id: {
                    type: 'string'
                },
                bucket_id: {
                    type: 'string'
                },
                path_tokens: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                },
                metadata: {
                    type: 'object',
                    properties: {
                        size: {
                            type: 'number'
                        },
                        mimetype: {
                            type: 'string'
                        },
                        eTag: {
                            type: 'string'
                        }
                    },
                    required: ['size', 'mimetype', 'eTag']
                }
            },
            required: ['id', 'bucket_id', 'path_tokens', 'metadata']
        },
        old_record: {}
    },
    required: ['type', 'table', 'schema', 'record'],
    example: {
        type: 'INSERT',
        table: 'objects',
        record: {
            id: '8f4611db-c346-4959-b173-681156612bfd',
            name: '2ba8848c-1639-563a-a559-959fa25c70bd/2',
            owner: null,
            version: '5dac074f-fc41-420d-ab03-5ab04ef42961',
            metadata: {
                eTag: '"f1cd0725ddb77f5a67a508cc48c8e554"',
                size: 16085011,
                mimetype: 'application/pdf',
                cacheControl: 'no-cache',
                lastModified: '2025-02-27T15:58:44.284Z',
                contentLength: 16085011,
                httpStatusCode: 200
            },
            owner_id: null,
            bucket_id: 'replica_files',
            created_at: '2025-02-27T15:58:44.501551+00:00',
            updated_at: '2025-02-27T15:58:44.501551+00:00',
            path_tokens: ['2ba8848c-1639-563a-a559-959fa25c70bd', '2'],
            user_metadata: {},
            last_accessed_at: '2025-02-27T15:58:44.501551+00:00'
        },
        schema: 'storage',
        old_record: null
    }
} as const;

export const knowledgeBaseID_parameterSchema = {
    type: 'number',
    description: 'The unique identifier of the knowledge base entry',
    example: '12345'
} as const;