// This file is auto-generated by @hey-api/openapi-ts

export const _replicaUUID__parameterSchema = {
    type: 'string',
    format: 'uuid',
    description: 'The UUID of the Replica',
    example: '03db5651-cb61-4bdf-9ef0-89561f7c9c53'
} as const;

export const The_linked_accounts_of_the_userSchema = {
    type: 'array',
    items: {
        type: 'object',
        properties: {
            accountID: {
                type: 'string',
                description: 'The account ID'
            },
            accountType: {
                type: 'string',
                enum: ['discord', 'telegram', 'embed'],
                description: 'The account type',
                example: 'discord'
            }
        },
        required: ['accountID', 'accountType']
    }
} as const;