import type { AutoChatActionFlavor } from '@grammyjs/auto-chat-action'
import type { FileFlavor } from '@grammyjs/files'
import type { Api, Bot, Context, RawApi } from 'grammy'
import { botActions } from './bot-actions'
import { hasUserRepliedToReplica } from './helpers'
import { parse } from './helpers'
import { getV1UsersMe, postV1ReplicasByReplicaUuidChatHistoryTelegram } from '../../client/sdk.gen'
import { initTelegramBot } from './bot-actions'
import { env } from 'node:process'

const SENSAY_API_KEY = env.SENSAY_API_KEY
const SENSAY_ORGANIZATION_SECRET = env.SENSAY_ORGANIZATION_SECRET
const VERCEL_PROTECTION_BYPASS_KEY = env.VERCEL_PROTECTION_BYPASS_KEY

type MyContext = FileFlavor<Context & AutoChatActionFlavor>
type MyBot = Bot<MyContext, Api<RawApi>>

export class BotClient {
  private readonly bot: MyBot
  private readonly replicaUuid: string
  private readonly ownerUuid: string

  constructor(botToken: string, replicaUuid: string, ownerUuid: string) {
    this.replicaUuid = replicaUuid
    this.ownerUuid = ownerUuid
    this.bot = initTelegramBot(botToken)
  }

  isHealthy() {
    return this.bot.isInited() && this.bot.isRunning()
  }

  async start() {
    await this.bot.init()

    this.bot.on('message', async (ctx, next) => {
      const parsedMessage = parse(ctx.message, ctx)
      if (!parsedMessage) return
      const {
        messageText,
        messageId,
        chatId,
        messageThreadId,
        type,
        isBot,
        userId,
        username,
        reply,
      } = parsedMessage

      if (isBot) return

      await checkAndCreateUser(ctx.from?.id.toString() || '')

      const isReplicaTagged = messageText.includes(`@${this.bot.botInfo.username}`)
      const isPrivateChat = type === 'private' // TODO: MICHELE: magic string

      const needsReplyByReplica =
        hasUserRepliedToReplica(reply, ctx.me.username) || isReplicaTagged || isPrivateChat

      // Save message on database and don't respond
      if (!needsReplyByReplica) {
        await postV1ReplicasByReplicaUuidChatHistoryTelegram({
          path: { replicaUUID: this.replicaUuid },
          body: {
            content: messageText,
            telegram_data: {
              chat_id: chatId,
              chat_type: type,
              user_id: userId,
              username: username || '',
              message_id: messageId,
              message_thread_id: messageThreadId,
            },
          },
        })

        return
      }

      await next()
    })

    botActions({
      bot: this.bot,
      botUsername: this.bot.botInfo.username,
      replicaUuid: this.replicaUuid,
      overridePlan: false,
      ownerUuid: this.ownerUuid,
      elevenlabsId: null,
      needsReply: true,
    })

    this.bot.catch((err) => {
      console.error('Failed to start bot', err)
    })

    this.bot.start({ // Don't await bot.start method. It blocks until the bot is stopped. https://grammy.dev/ref/core/bot#start
      onStart: (botInfo) => {
        console.log(`@${botInfo.username} is running\n`)
      },
    })
  }

  async stop() {
    await this.bot.stop()
  }
}

interface ErrorResponse {
  error?: string
  message?: string
}

async function checkAndCreateUser(userId: string) {
  try {
    // First, try to get the user using the users/me endpoint
    const userResponse = await getV1UsersMe({
      headers: {
        'Content-Type': 'application/json', // TODO: MICHELE: DRY
        'X-ORGANIZATION-SECRET': SENSAY_ORGANIZATION_SECRET || '',
        'X-USER-ID': userId,
        'X-USER-ID-TYPE': 'telegram',
        'x-vercel-protection-bypass': VERCEL_PROTECTION_BYPASS_KEY || '',
      },
    })

    // If the response is successful, the user exists
    if (userResponse.response.ok) {
      return userResponse.data
    }

    // If we get a 401 error, the user doesn't exist and we need to create them
    if (userResponse.response.status === 401) {
      const createResponse = await fetch(`${SENSAY_API_KEY}/v1/users`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-ORGANIZATION-SECRET': SENSAY_ORGANIZATION_SECRET || '',
          'x-vercel-protection-bypass': VERCEL_PROTECTION_BYPASS_KEY || '',  // Needed to connect to non-production environments
        },
        body: JSON.stringify({
          IDs: [
            {
              userID: userId,
              userIDType: 'telegram', // TODO: MICHELE: magic string. Is it not generated by the SDK?
            },
          ],
        }),
      })

      if (!createResponse.ok) {
        const errorData = (await createResponse.json()) as ErrorResponse
        throw new Error(errorData.error || errorData.message || 'Failed to create user') // TODO: MICHELE: errorData suppressed if not recognized
      }

      console.log('User created') // TODO: MICHELE: say which user was generated?

      return await createResponse.json()
    }

    // For other error statuses, throw an error
    const errorData = userResponse.error as ErrorResponse // TODO: MICHELE: Does it work?
    throw new Error(
      errorData.error || errorData.message || `Unexpected error: ${userResponse.response.status}`, // TODO: MICHELE: different error handling pattern. unify
    )
  } catch (error: unknown) {
    // Re-throw the error with additional context
    if (error instanceof Error) {
      throw new Error(`Error checking/creating user: ${error.message}`) // TODO: MICHELE: cause lost
    }
    throw new Error(`Error checking/creating user: ${String(error)}`) // TODO: MICHELE: same as above
  }
}
